### ISSUE TITLE
Why not simply calling this repository ndarray?

### ISSUE THREAD

**Issue by nbro** [bluss/ndarray#423]
Given that Rust (and I suppose this repository/crate too) is still in its early phases, the advantages one may obtain to simplify the name now may be more than the disadvantages (e.g. breaking a few links).

**Comment by bluss** [comment]
Sure this one is easily actionable; github has redirects from the old name so it should be very painless.

**Comment by nbro** [comment]
See: https://github.com/bluss/ndarray/pull/430.
