### ISSUE TITLE
Broadcasting limitations / Custom strides?

### ISSUE THREAD

**Issue by davenza** [bluss/ndarray#437]
Hi, I have a problem that I don't know how to solve with the current [broacast](https://docs.rs/ndarray/0.11.2/ndarray/struct.ArrayBase.html#method.broadcast) implementation.

I want to multiply two matrices where some axis in both matrices could have length 1. For example:

`shape [1,2,2] * shape [2,1,2]`

The expected matrix would be a `shape [2, 2, 2]`. #265 illustrates this behaviour better than me.  This is totally natural in Numpy. Of course, the current implementation of ndarray does not allow this type of operations and @bluss commented that was not keen to implement it.

-----------------
## Custom strides?
I have been thinking how to solve this problem, and the unique (efficient) solution that I could come up is using custom strides where the stride is 0 in the axis with length 1. So, our original matrices:

`shape [1,2,2], strides [4,2,1] * shape [2,1,2], strides[4,2,1]`

would be converted to:

`shape [2,2,2], strides [0,2,1] * shape [2,1,2], strides[4,2,1]`

Note that only the left matrix needs to be customized. However, the current [ArrayBase](https://docs.rs/ndarray/0.11.2/ndarray/struct.ArrayBase.html) implementation does not allow changes on the strides. The unique way to customize strides is: [from_shape_vec](https://docs.rs/ndarray/0.11.2/ndarray/struct.ArrayBase.html#method.from_shape_vec). However, as the documentation states: 

`Errors if strides allow multiple indices to point to the same element`, so this type of changes are not allowed. How would you solve this problem?

**Comment by davenza** [comment]
Thank you @jturner314! That solves my problems with broadcasting.

Now, this could be another issue, but I have compared the performance of ndarray and Numpy and the results are very surprising to me:

i7 6700k 32GB 1867Mhz
-------------------------------------------

| n   | Python    | Rust      |
|----|-----------|-----------|
| 2  | 0.85 us  | 0.87 us  |
| 4  | 1.11 us  | 4.12 us  |
| 6  | 1.83 us  | 21.22 us  |
| 8  | 6.55 us  | 176.76 us  |
| 10 | 35.36 us  | 1.41 ms |
| 12 | 230.48 us  | 12.05 ms |


The benchmark code is [here](https://github.com/davenza/ndarray_vs_numpy), if you wish to check it. In this benchmark I multiplied two arrays with 2^{n} elements. I added n/2 axes with length 1 on each array. In one array, the axes were added at the start. In the other array, the axes were added at the end. The expected result is going to have 2^{n + n / 2} elements.

Of course, the problem is exponential with n. Python's solution is way, way more performant. I know that Numpy is really mature and it is a great piece of work (with huge amounts of C code), but the difference seems like black magic coming from the Numpy devs.

Maybe am I doing something wrong? I added blas support in the rust project. However, it does not make any difference in the performance results (not worse, not better). That is weird to me, because blas should be pretty optimized I guess.

Thank you again for your help and support!

**Comment by davenza** [comment]
Thank you again @jturner314. Your suggestions are always good.

I didn't prepare the benchmark to compare ndarray and Numpy in general. The benchmark was created because I need that functionality on one of my projects. I understand that the library and the language itself should be more mature to compete against Numpy.
 
So thanks again, and keep the good work!

**Comment by jturner314** [comment]
@davenza You're welcome. I hope `ndarray` works well for you!

It seems like this issue is resolved, so I'm closing it. If there's anything else, please feel free to reopen this issue or open a new one.
