### ISSUE TITLE
Question : Matrices subtraction similar to numpy

### ISSUE THREAD

**Issue by rohitjoshi** [bluss/ndarray#439]
In numpy y-mu returns as below
```
mu=[-1.35900258, -0.00274826, -0.60259734]
y=[[-1.16850298],
 [-0.71405641],
 [-1.84973747]]

r = y-mu
print("y-mu=" + str(r))
y-mu = [[ 0.1904996  -1.16575472 -0.56590564]
 [ 0.64494618 -0.71130814 -0.11145907]
 [-0.49073488 -1.8469892  -1.24714013]]
```

How do I achieve same in ndarray?

```
mu=[-0.25304218713684945, 0.12751433863551823, 0.3773315624850666]
y= [[0.41651350674857823]]
y-mu gives error 
thread 'main' panicked at 'ndarray: could not broadcast array from shape: [3] to: [1, 1]'
```

**Comment by rohitjoshi** [comment]
I tried few ways without any success. Would appreciate your help.

**Comment by jturner314** [comment]
See #437 for a similar question, in particular [this response](https://github.com/bluss/ndarray/issues/437#issuecomment-380654011). Basically, one solution is to broadcast the left array (`y` in your example) to the size of the result, and then perform the operation.

**Comment by jturner314** [comment]
@rohitjoshi Do you have any more questions about this? Otherwise, I'll close this issue.

**Comment by rohitjoshi** [comment]
No, thx
