### ISSUE TITLE
ndarray 0.11.2 makes nightly clippy abort

### ISSUE THREAD

**Issue by dfannius** [bluss/ndarray#454]
`rustc 1.27.0-nightly (2f2a11dfc 2018-05-16)`
`cargo 1.27.0-nightly (9e53ac6e6 2018-05-07)`

Here is my entire program:
```
extern crate ndarray;

fn main() {
    let m = ndarray::arr2(&[[1., 2., 3.], [4., 6., 8.]]);
    println!("{}", m);
}
```
and the entire `[dependencies]` portion of `Cargo.toml`:
```
[dependencies]
ndarray = "0.11"
```

When I attempt to run clippy, this is the result:
```
$ cargo +nightly clippy
    Checking ndarray v0.11.2
error[E0277]: the trait bound `S: data_traits::Data` is not satisfied
   --> /Users/dschmidt/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.11.2/src/lib.rs:655:5
    |
655 |     ptr: *mut S::Elem,
    |     ^^^^^^^^^^^^^^^^^ the trait `data_traits::Data` is not implemented for `S`
    |
    = help: consider adding a `where S: data_traits::Data` bound

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `ndarray`.

To learn more, run the command again with --verbose.
```

If this is user error or there is an easy workaround, I would love to know the solution. Thanks.

**Comment by dfannius** [comment]
For what it's worth, `cargo +nightly build` works fine. Maybe this is a clippy bug and I should take it there?

**Comment by jturner314** [comment]
I haven't had a chance to investigate, but I would call this a `clippy` bug. `cargo +nightly clippy` shouldn't give build errors when `cargo +nightly build` doesn't give any errors.

**Comment by dfannius** [comment]
I will take it there, then. Thanks.
