### ISSUE TITLE
How to inverse a 3x3 matrix?

### ISSUE THREAD

**Issue by dineshadepu** [bluss/ndarray#465]
Hi,

I am using ndarray for rigid body simulation. I have moment of inertia matrix, I need to take an inverse.
Right now I don't know how to do it in ndarray. I guess, I should be using BLAS. But I don't know. 

Can some one help.

**Comment by nilgoyette** [comment]
ndarray doesn't offer [a lot of] tools for linear algebra. You can check [ndarray-linalg](https://crates.io/crates/ndarray-linalg) though. Or even [nalgebra](https://crates.io/crates/nalgebra) if you don't care about converting your array from ndarray to nalgebra. In fact, if you only need hardcoded size matrices in your project, nalgebra **may** be a better tool for you.

**Comment by dineshadepu** [comment]
I found a function on SquareMatrix, `invert`, which computes the inverse. I think I can use that.

What do you say?

**Comment by SuperFluffy** [comment]
You have to be more specific. What is `SquareMatrix` and what do you want us to answer about it? If by `SquareMatrix` you mean the the newtype from `nalgebra`, then your question might be more appropriate there.

**Comment by dineshadepu** [comment]
Sorry, I was seeing cgmath library and got confused with this.
