### ISSUE TITLE
any() and all()

### ISSUE THREAD

**Issue by tsoernes** [bluss/ndarray#468]
In numpy, doing `arr.any()` returns (short-circuiting) if any element in the array is `true`. Similarly for `all`. Do these exist in ndarray (I could not find them), if not, can I request them?

**Comment by nilgoyette** [comment]
They don't exist in ndarray, but they exist in [Iterator](https://doc.rust-lang.org/std/iter/trait.Iterator.html): [all](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.all) and [any](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.any)

You can call [iter](https://docs.rs/ndarray/0.11.2/ndarray/struct.ArrayBase.html#method.iter) on your array then use all the methods you want that are defined in the trait Iterator. Something like

    if a.iter().any(|&v| v > 4.0) { println!("yeah") }
    if a.iter().any(my_func) { ... }

**Comment by tsoernes** [comment]
Very good, thank you.
