### ISSUE TITLE
Checking the number of axes

### ISSUE THREAD

**Issue by LukeMathWalker** [bluss/ndarray#488]
I was looking at the `Dimension` trait: there is a `ndim` method which is marked with `#[doc(hidden)]` in the trait definition:
```
#[doc(hidden)]
    fn ndim(&self) -> usize;
```
Why is this the case? Is it somehow NOT the "right" way of checking how many axes an array has at runtime?

**Comment by jturner314** [comment]
If you have an instance of `ArrayBase`, you can use `ArrayBase`'s `ndim` method. Note also the `NDIM` associated constant on the `Dimension` trait. However, if you want to know the number of elements in an arbitrary `D: Dimension` instance, there isn't a great way to do that right now (best solution using non-hidden methods is `dim.as_array_view().len()`).

I'm not sure why `Dimension::ndim` method is currently hidden; I assume it's that way just to minimize the size of the public API. I am in favor of exposing the `Dimension::ndim` method.

**Comment by LukeMathWalker** [comment]
The `NDIM` constant is great to do compile-time checks, but it returns `None` for dynamic dimensions, where `ndim` instead provides the actual value at runtime.

If we are ok with exposing it I can file a PR.
