### ISSUE TITLE
Replace LinalgScalar by num_traits::Num

### ISSUE THREAD

**Issue by termoshtt** [bluss/ndarray#499]
`ndarray::linalg_traits::LinalgScalar` and `num_traits::Num` are basically same trait. num-traits 0.2 has more specific traits i.e. `Num`, `NumOps`, `NumRef`, `NumAssign`, `NumAssignOps` and `NumAssignRef`. `LinalgScalar` is merely used in this crate, and it exists for user convenience. Should we replace `LinalgScalar` by `Num`?

**Comment by jturner314** [comment]
`ndarray::LinalgScalar` requires the following: `'static + Copy + Zero + One + Add + Sub + Mul + Div`. I think we could probably eliminate the `Copy` bound, but we can't really get rid of the `'static` bound right now. (See jturner314/ndarray-stats#3 for the reasoning for keeping `'static`.)

`num_traits::Num` requires the following: `PartialEq + Zero + One + Add + Sub + Mul + Div + Rem`.

So, we could replace `LinalgScalar` bounds with `'static + Copy + Num`, or possibly `'static + Num`. To be honest, though, I don't really see any reason to do so. `LinalgScalar` is automatically implemented for `T` where `T` meets the required bounds, so it's not an issue of convenience. If we switch to `'static + Copy + Num`, we're adding unnecessary `Num + Rem` bounds (and note that `Num` has to be implemented for the specific type, unlike `LinalgScalar` which is implemented for `T`).

Is there any reason in particular to make this change?

**Comment by termoshtt** [comment]
Your comment for `'static` is quite reasonable.

> Is there any reason in particular to make this change?

The generalization of number types is responsible for the num-traits crate. IMO, we should not introduce a trait for fine-tuned minimal requirement (`LinalgScalar`) rather than using commonly used trait (`'static + Num`).

> If we switch to 'static + Copy + Num, we're adding unnecessary Num + Rem bounds

This is actually problematic...
num-complex::Complex had been lacking these traits long time until https://github.com/rust-num/num/pull/327. `Num` is not a large problem, but `Rem` is sometimes hard to implement.

**Comment by jturner314** [comment]
We could use `'static + Copy + NumOps` to avoid the `Num` requirement, but `NumOps` still requires `Rem`. It looks like all of the relevant `num-traits` traits require `Rem`.

**Comment by termoshtt** [comment]
I make sense the difference of LinalgScalar and Num. Thanks.
